dataset_name: 'flo'
window: 30

detrend: False
scale: True
scaling_axis: 'channels'
scaled_target: True

epochs: 300
samples_per_epoch: 1360  # 160 batch of 32
lr: 0.0005
batch_size: 16
aggregate_by: ['mean']

model_name: 'var'
order: 5
padding: 'mean'